server:
    port: 8080
spring:
    application:
        name: customer
    datasource:
        username: postgres
        url: jdbc:postgresql://localhost:2345/customer
        # if when we start the applcation name it is a container then instead of localhost it would be - the network name - I think
        password: password
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: create-drop
#        ddl-auto: update
      show-sql: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
#        enabled: false
        
#    zipkin:
#        base-url: http://localhost:9411
#    rabbitmq:
#        addresses: localhost:5672
