spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    


#  zipkin:
#    base-url: http://localhost:9411
